#!/bin/bash

protein_dir="/home/dalsasso/data/References/proteomes/"
tmhmm_output_dir="/home/dalsasso/annotations/tmhmm/"


for protein_file in "$protein_dir"*no_stop_codon.fa; do
   
    base_name=$(basename "$protein_file" | cut -d_ -f1)

    /home/dalsasso/softwares/TMHMM/tmhmm-2.0c/bin/tmhmm  "$protein_file" > "${tmhmm_output_dir}${base_name}.tmhmm.out"
done



